name: dartwindows_lints
description: A set of lint rules used by the Dart | Windows organization.
version: 1.1.0
repository: https://github.com/dart-windows/dartwindows_lints

topics:
  - analysis
  - lints

environment:
  sdk: ^3.1.0

dependencies:
  lints: ^3.0.0
